spring:
  cloud:
    gateway:
      routes:
      - id: r1
        uri: http://localhost:8081/
        predicates:
        - Path= /enseignants/**
      - id: r2
        uri: http://localhost:8082/
        predicates:
        - Path= /annonces/**
      - id: r3
        uri: http://localhost:8017/
        predicates:
        - Path= /courses/**
      